Ignore `p` and `p-span` components in add at macro script
day8/re-com pull request #268
Opened 2021-03-26 14:48 UTC by MawiraIke

Fixes #267

2021-03-26 22:34 UTC, superstructor requested changes

2021-03-26 22:34 UTC, superstructor commented on scripts/add-at-macro/src/add_at_macro/core.clj
> +   - Given the string `rc/p` and the alias `rc`, will return true
won't it be `false` ?

2021-03-26 22:34 UTC, superstructor commented on scripts/add-at-macro/src/add_at_macro/core.clj
> +   - Given the string `rc/p-span` and the alias `rc`, will return true
won't it be `false` ?

2021-03-26 22:34 UTC, superstructor commented on scripts/add-at-macro/src/add_at_macro/core.clj
> +   - Given any other string such as `rc/box` and an alias such as `rc` will return false"
won't it be `true` ?

2021-03-26 22:34 UTC, superstructor commented on scripts/add-at-macro/src/add_at_macro/core.clj
> +(defn re-com-component?
fn needs a better name. 

maybe re-com-kwargs-component? or component-accepts-kwargs?

2021-03-27 04:46 UTC, MawiraIke commented
@superstructor thanks, I have resolved the issues now. Should be good to go.

2021-03-28 10:16 UTC, merged

2021-03-28 10:16 UTC, superstructor commented
Thanks @MawiraIke 👍🏻 😄