Add script to convert kwargs to map with hiccup like syntax
day8/re-com pull request #276
Opened 2021-04-02 06:55 UTC by MawiraIke

Adds script  and fixes #275

2021-04-02 08:13 UTC, MawiraIke commented
Fair to note that the re-com components are edited as follows;
- The re-com components, `p` and `p-span` do not receive any editing
- The re-com components below are considered to have the child which is the indicated key
`modal-panel`        -> `:child`
`alert-box`              -> `:body`
`box`                      -> `:child`
`scroller`                -> `:child`
`border`                 -> `:child`
`checkbox`             -> `:label`
The keyword args are added to a map and then the child is added after.
For example the `box`
```Clojure
[re-com/box :src (at)
  :size "1"
  :child [border
          :border "1px dashed red"
          :child  [box :height "100px" :child "Hello"]]
  :align :center]
```
is transformed to 
```Clojure
[re-com/box { :src (at)                                                        <== the map is added
  :size "1"
  :align :center } [border                                                     <== child is conjoined after the map
          :border "1px dashed red"
          :child  [box :height "100px" :child "Hello"]]]
```
Space is not preserved after the first child

- The following re-com components are assumed to have the key `:children`
`h-box`
`v-box`
The keyword arguments are added to a map and then children are added recursively after
For example the `v-box` below
```Clojure
[v-box :src (at)
 :size    "1"
 :justify  :center
 :children [[re-com/v-box :src (at)
             :size     "1"
             :children [[label :title "Moved"]]
             :align    :center]
```
is transformed to
```Clojure
[v-box { :src (at)                                                         <== map is added
 :size     "1"
 :justify  :center } [re-com/v-box :src (at)                   <== children are added after the map
             :size     "1"
             :children [[label :title "Moved"]]
             :align    :center]
```
Note that space is not preserved in the children


- The following are treated as splits
`h-split`
`v-split`
The keys `:panel-1` and `panel-2` are added in the right order outside the map
For example consider the `h-split`
```Clojure
[rc/h-split :src (at)
 :panel-1 [left-panel]
 :panel-2 [right-panel]
 :size    "300px"]
```
It is transformed to
```Clojure
[rc/h-split { :src (at)                                                                      <== the map is added
 :size    "300px" } [left-panel] [right-panel]]                                 <== the panels are added after the map
```
Space is preserved within the map

- All other components are treated as to have no special reformatting and all their keyword arguments are wrapped in a map preserving whitespace.
For example a button like
```Clojure
[button
 :label    "This is the label"
 :style    {:color "red"}
 :on-click nil
 :class    "class-name"]
```

is edited as follows
```Clojure
[button {                                                        <== the map is added
 :label    "This is the label"
 :style    {:color "red"}
 :on-click nil
 :class    "class-name" } ]
```

2021-04-07 10:51 UTC, mike-thompson-day8 commented
The detail you provide above should be included at the end of the README

2021-04-07 22:48 UTC, superstructor requested changes
noted some changes, also please add docopt ala add add macro script

2021-04-07 22:48 UTC, superstructor commented on scripts/kwargs-to-map/.gitignore
> +/.nrepl-port
delete the .gitignore

2021-04-07 22:48 UTC, superstructor commented on scripts/kwargs-to-map/README.md
> +You should run this script on a legacy codebase to convert keyword arguments in re-com components to a map.
Add a massive warning at the top of this README.md as a heading:

WARNING: Do NOT use this script. It has been created in preparation for a future re-com change. No version of re-com (including `master` branch) is yet compatible with the changes made by this script.

And delete "You should run this script... " paragraph.

2021-04-07 22:48 UTC, superstructor commented on scripts/kwargs-to-map/README.md
> +[v-box  { :src  (at)            ;; <-- this is wrapped in a map
This example is for the at macro.

2021-04-07 22:48 UTC, superstructor commented on scripts/kwargs-to-map/README.md
> +This project uses [babashka](https://github.com/babashka/babashka) which will need to be pre-installed.
incl babashka version ala add at macro readme

2021-04-07 22:48 UTC, superstructor commented on scripts/kwargs-to-map/README.md
> +   bb src\kwargs-to-map\core.clj "../my-project/src"
drop the `src/kwargs-to-map`. Rename to `kwargs_to_map.clj`

2021-04-07 22:48 UTC, superstructor commented on scripts/kwargs-to-map/project.clj
> +(defproject kwargs-to-map "0.1.0-SNAPSHOT"
This is not a lein project, it is a babashka project, delete the `project.clj`

2021-04-07 22:48 UTC, superstructor commented on scripts/kwargs-to-map/test/kwargs_to_map/core_test.clj
> +(ns kwargs-to-map.core-test
move this file ala at add macro layout

2021-04-07 22:48 UTC, superstructor commented on scripts/kwargs-to-map/src/kwargs_to_map/core.clj
> +#!/usr/bin/env bb
move this file ala add at macro layout

2021-04-07 22:48 UTC, superstructor commented on scripts/kwargs-to-map/test/kwargs_to_map/core_test.clj
> +
this file actually need assertions ala the add at macro scirpt, not just printing the results to console

2021-04-08 07:24 UTC, MawiraIke commented
Thanks @mike-thompson-day8 @superstructor I have merged your suggestions to the latest commit

2021-04-08 13:20 UTC, superstructor commented
Nice, thanks @MawiraIke 👍🏻 😄

2021-04-08 13:20 UTC, merged